---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/v1/contacts":
    get:
      summary: list contacts
      responses:
        '200':
          description: successful
    post:
      summary: create contact
      responses:
        '200':
          description: successful
  "/api/v1/contacts/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: show contact
      responses:
        '200':
          description: successful
    patch:
      summary: update contact
      responses:
        '200':
          description: successful
    put:
      summary: update contact
      responses:
        '200':
          description: successful
    delete:
      summary: delete contact
      responses:
        '200':
          description: successful
  "/api/v1/customers":
    get:
      summary: list customers
      responses:
        '200':
          description: successful
    post:
      summary: create customer
      parameters: []
      responses:
        '200':
          description: successful
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                fantasy_name:
                  type: string
                customer_name:
                  type: string
                tax_id:
                  type: string
                status:
                  type: boolean
                state_registration:
                  type: string
              required:
              - customer_name
              - tax_id
              - state_registration
  "/api/v1/customers/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: Retrieves a Customer
      responses:
        '200':
          description: blog found
          content:
            application/json:
              schema:
                type: object
                properties:
                  fantasy_name:
                    type: string
                  customer_name:
                    type: string
                  tax_id:
                    type: string
                  status:
                    type: boolean
                  state_registration:
                    type: string
                required:
                - id
                - title
                - content
            application/xml:
              schema:
                type: object
                properties:
                  fantasy_name:
                    type: string
                  customer_name:
                    type: string
                  tax_id:
                    type: string
                  status:
                    type: boolean
                  state_registration:
                    type: string
                required:
                - id
                - title
                - content
        '404':
          description: blog not found
        '406':
          description: unsupported accept header
      tags:
      - Customers
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
    patch:
      summary: update customer
      parameters: []
      responses:
        '200':
          description: successful
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                fantasy_name:
                  type: string
                customer_name:
                  type: string
                tax_id:
                  type: string
                status:
                  type: boolean
                state_registration:
                  type: string
    put:
      summary: update customer
      parameters: []
      responses:
        '200':
          description: successful
    delete:
      summary: delete customer
      responses:
        '200':
          description: successful
  "/api/v1/facilities":
    get:
      summary: list facilities
      responses:
        '200':
          description: successful
    post:
      summary: create facility
      responses:
        '200':
          description: successful
  "/api/v1/facilities/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: show facility
      responses:
        '200':
          description: successful
    patch:
      summary: update facility
      responses:
        '200':
          description: successful
    put:
      summary: update facility
      responses:
        '200':
          description: successful
    delete:
      summary: delete facility
      responses:
        '200':
          description: successful
  "/api/v1/operations":
    get:
      summary: list operations
      responses:
        '200':
          description: successful
    post:
      summary: create operation
      responses:
        '200':
          description: successful
  "/api/v1/operations/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: show operation
      responses:
        '200':
          description: successful
    patch:
      summary: update operation
      responses:
        '200':
          description: successful
    put:
      summary: update operation
      responses:
        '200':
          description: successful
    delete:
      summary: delete operation
      responses:
        '200':
          description: successful
servers:
- url: http://{defaultHost}
  variables:
    defaultHost:
      default: localhost:3000
