---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/v1/customers":
    get:
      summary: list customers
      responses:
        '200':
          description: successful
    post:
      summary: create customer
      responses:
        '200':
          description: successful
  "/api/v1/customers/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: show customer
      responses:
        '200':
          description: successful
    patch:
      summary: update customer
      responses:
        '200':
          description: successful
    put:
      summary: update customer
      responses:
        '200':
          description: successful
    delete:
      summary: delete customer
      responses:
        '200':
          description: successful
servers:
- url: https://{defaultHost}
  variables:
    defaultHost:
      default: www.example.com
